language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  skip_cleanup: true
  email: vikingmute@gmail.com
  api_key:
    secure: dHs0HC9aOtDCwdfbiV5PD2T3hN0g10/looEs8fO7GnRlwH8wGsy9NaVrz8pxZeG9eqVYV/oMDjoo+Cmy1H+bpyPRjS4EbzDSBSmGXkj38j3nQ60HH2ViwX0XMROP4hJFqTdbKy5ALDwJIhq+vGPNYZSiUtc1fOTWp/a1dloprmK8GuxchEA2B4AFGureswtP1EO8cPYdI9UNDh7Z0L9O6ewLyx53mYaRMrNKV4qAi8UxPUBsWj4EFHQ8PCBKY2hAa2UnLEcXKZ5o43v7YymMtYEgfpO9I8eyxsYnDsk0Fur0+NDwW0UlCWJKnwPEFEI/TgL7daKjkG3MP9QOWy7fED8sDzGxjgElxCOtkH9m/g9uEn8H/hJ+ryYpDcKcepDsqARW0a5ZbjB4iPqTFaQpoNWZZvqeOi6IvQcXbtg229buQ6zQdKW9rmiVns1cAP3U2utIJ4Ac517LkFr2AvXO+bxkRvyPcJYwjHhQlsf8GV4WmXN7pCEFepeAUqGjJ3UmX66etkG4phl2+6RPf93pRAD1cpSfcROEVQvh8tLKDvKRL47F0u+l6mosZQuF7dIhXqzzj/YjtwTB874N29Xx74e4YXsHJeixdPgC9oxvBTOiEAtGY1RHnWgqNVBY7eZXFPzfOf6iXtl3kmqsL1rm7S4ZxG9bxd5purUQ3VpR1Wg=
  on:
    tags: true
